export const Producto = [
  // Hidratantes
  {
    id: 1,
    nombre: "Exótico de Mango",
    tamaño: "1.5L",
    img: "https://res.cloudinary.com/dleem7osr/image/upload/e_background_removal/f_png/v1733244460/greenDetox_u9xnq5.png",
    descripcion: "Refrescante bebida a base de mango con un toque tropical.",
    precio: "14.00",
    categoria: "Botella",
    tipo: "hidratante",
  },
  {
    id: 2,
    nombre: "Limonada Detox",
    tamaño: "500ml",
    img: "https://drinkprime.com/cdn/shop/files/Speed-Bottle-Front_b2fe6348-b16b-4582-b0fb-c2f3efcc2bc5_2000x.png?v=1727210047",
    descripcion: "Refrescante limonada con jengibre y menta para desintoxicar tu cuerpo.",
    precio: "12.00",
    categoria: "Botella",
    tipo: "hidratante",
  },
  {
    id: 3,
    nombre: "Hidratante de Coco",
    tamaño: "1L",
    img: "https://res.cloudinary.com/dleem7osr/image/upload/e_background_removal/f_png/v1733244460/greenDetox_u9xnq5.png",
    descripcion: "Bebida refrescante a base de coco natural para una hidratación óptima.",
    precio: "16.00",
    categoria: "Botella",
    tipo: "hidratante",
  },
  {
    id: 4,
    nombre: "Agua de Jamaica",
    tamaño: "500ml",
    img: "https://drinkprime.com/cdn/shop/files/Speed-Bottle-Front_b2fe6348-b16b-4582-b0fb-c2f3efcc2bc5_2000x.png?v=1727210047",
    descripcion: "Infusión de flor de jamaica, refrescante y antioxidante.",
    precio: "12.50",
    categoria: "Botella",
    tipo: "hidratante",
  },
  {
    id: 5,
    nombre: "Hidratante de Piña",
    tamaño: "1L",
    img: "https://res.cloudinary.com/dleem7osr/image/upload/e_background_removal/f_png/v1733244460/greenDetox_u9xnq5.png",
    descripcion: "Bebida refrescante con jugo natural de piña, ideal para mantenerte hidratado.",
    precio: "14.50",
    categoria: "Botella",
    tipo: "hidratante",
  },
  {
    id: 6,
    nombre: "Limonada de Pepino",
    tamaño: "500ml",
    img: "https://drinkprime.com/cdn/shop/files/Speed-Bottle-Front_b2fe6348-b16b-4582-b0fb-c2f3efcc2bc5_2000x.png?v=1727210047",
    descripcion: "Limonada refrescante con pepino y hierbabuena, perfecta para el calor.",
    precio: "13.00",
    categoria: "Botella",
    tipo: "hidratante",
  },

  // Energizantes
  {
    id: 7,
    nombre: "Energizante de Naranja",
    tamaño: "500ml",
    img: "https://drinkprime.com/cdn/shop/files/swsticksfront_200x.png?v=1689354735",
    descripcion: "Bebida revitalizante hecha con jugo de naranja y jengibre.",
    precio: "10.00",
    categoria: "Botella",
    tipo: "energizante",
  },
  {
    id: 8,
    nombre: "Té Matcha en Polvo",
    tamaño: "250g",
    img: "https://drinkprime.com/cdn/shop/files/Speed-Bottle-Front_b2fe6348-b16b-4582-b0fb-c2f3efcc2bc5_2000x.png?v=1727210047",
    descripcion: "Polvo de té verde japonés, ideal para bebidas energizantes y antioxidantes.",
    precio: "20.00",
    categoria: "Polvo",
    tipo: "energizante",
  },
  {
    id: 9,
    nombre: "Cacao Energizante en Polvo",
    tamaño: "300g",
    img: "https://drinkprime.com/cdn/shop/files/Speed-Bottle-Front_b2fe6348-b16b-4582-b0fb-c2f3efcc2bc5_2000x.png?v=1727210047",
    descripcion: "Cacao orgánico combinado con superalimentos para mayor energía.",
    precio: "28.00",
    categoria: "Polvo",
    tipo: "energizante",
  },
  {
    id: 10,
    nombre: "Bebida de Guaraná",
    tamaño: "500ml",
    img: "https://drinkprime.com/cdn/shop/files/Speed-Bottle-Front_b2fe6348-b16b-4582-b0fb-c2f3efcc2bc5_2000x.png?v=1727210047",
    descripcion: "Bebida energizante natural con guaraná, ideal para aumentar el rendimiento.",
    precio: "18.00",
    categoria: "Botella",
    tipo: "energizante",
  },
  {
    id: 11,
    nombre: "Matcha Latte Energizante",
    tamaño: "200g",
    img: "https://drinkprime.com/cdn/shop/files/Speed-Bottle-Front_b2fe6348-b16b-4582-b0fb-c2f3efcc2bc5_2000x.png?v=1727210047",
    descripcion: "Matcha latte en polvo, con un toque energizante para tus mañanas.",
    precio: "22.00",
    categoria: "Polvo",
    tipo: "energizante",
  },

  // Nutricionales
  {
    id: 12,
    nombre: "Detox Verde",
    tamaño: "1L",
    img: "https://res.cloudinary.com/dleem7osr/image/upload/e_background_removal/f_png/v1733244460/greenDetox_u9xnq5.png",
    descripcion: "Bebida saludable hecha a base de vegetales verdes, ideal para eliminar toxinas.",
    precio: "15.00",
    categoria: "Botella",
    tipo: "nutricional",
  },
  {
    id: 13,
    nombre: "Proteico de Banana",
    tamaño: "1L",
    img: "https://drinkprime.com/cdn/shop/files/DreamPopFront_400x.png?v=1716568606",
    descripcion: "Bebida alta en proteínas, ideal para recuperar energía después de entrenar.",
    precio: "18.00",
    categoria: "Botella",
    tipo: "nutricional",
  },
  {
    id: 14,
    nombre: "Detox en Polvo",
    tamaño: "200g",
    img: "https://res.cloudinary.com/dleem7osr/image/upload/e_background_removal/f_png/v1733244460/greenDetox_u9xnq5.png",
    descripcion: "Polvo detox para preparar con agua o jugo. Ideal para limpiar el organismo.",
    precio: "25.00",
    categoria: "Polvo",
    tipo: "nutricional",
  },
  {
    id: 15,
    nombre: "Proteína Vegana de Cacao",
    tamaño: "500g",
    img: "https://drinkprime.com/cdn/shop/files/DreamPopFront_400x.png?v=1716568606",
    descripcion: "Proteína en polvo a base de cacao y plantas. Perfecta para dietas veganas.",
    precio: "35.00",
    categoria: "Polvo",
    tipo: "nutricional",
  },
  {
    id: 16,
    nombre: "Smoothie de Frutos Rojos",
    tamaño: "1L",
    img: "https://drinkprime.com/cdn/shop/files/Speed-Bottle-Front_b2fe6348-b16b-4582-b0fb-c2f3efcc2bc5_2000x.png?v=1727210047",
    descripcion: "Bebida rica en antioxidantes hecha con fresas, arándanos y frambuesas.",
    precio: "16.00",
    categoria: "Botella",
    tipo: "nutricional",
  }
];
