export const Producto = [
  // Hidratantes
  {
    id: 1,
    nombre: "Mango Splash",
    tamaño: "500ml",
    pack : "6 unidades",
    img: "https://res.cloudinary.com/dleem7osr/image/upload/v1733355043/MangoBebida-removebg-preview_oovd09.png",
    imgDos: "https://res.cloudinary.com/dleem7osr/image/upload/v1733355043/MangoBebida-removebg-preview_oovd09.png",
    imgTres: "https://th.bing.com/th/id/OIG4.nbNKrqhlj3WIg7AGx7sI?pid=ImgGn",
    descripcion: "Una bebida refrescante elaborada con extracto natural de mango, rica en antioxidantes y vitaminas esenciales. Sin conservantes artificiales, es la opción perfecta para hidratarte de manera natural .",
    precio: "19.99",
    categoria: "Botella",
    tipo: "hidratante",
  },
  {
    id: 2,
    nombre: "Naranja Splash",
    tamaño: "500ml",
    pack : "6 unidades",
    img: "https://res.cloudinary.com/dleem7osr/image/upload/v1733340286/BotellaEnergizanteN-removebg-preview_mge8w9.png",
    imgDos: "https://res.cloudinary.com/dleem7osr/image/upload/v1733340286/BotellaEnergizanteN-removebg-preview_mge8w9.png",
    imgTres: "https://res.cloudinary.com/dleem7osr/image/upload/v1733340286/BotellaEnergizanteN-removebg-preview_mge8w9.png",
    descripcion: "Una bebida energizante con jugo natural de naranja, enriquecida con vitaminas C y B. Refresca, revitaliza y brinda la energía necesaria para mantenerte en acción durante todo el día.",
    precio: "19.99",
    categoria: "Botella",
    tipo: "hidratante",
  },

  {
    id: 3,
    nombre: "Coconut Dew Splash",
    tamaño: "200ml",
    pack : "6 unidades",
    img: "https://res.cloudinary.com/dleem7osr/image/upload/v1733355671/CocoNuw-removebg-preview_hnv1rw.png",
    imgDos: "https://res.cloudinary.com/dleem7osr/image/upload/v1733355671/CocoNuw-removebg-preview_hnv1rw.png",
    imgTres: "https://i.ibb.co/LSjsbnZ/CocoNuw.jpg",
    descripcion: "Una bebida refrescante y natural con agua de coco pura, rica en electrolitos y minerales esenciales. Hidrata, revitaliza y te mantiene energizado de manera saludable, sin aditivos artificiales.",
    precio: "9.99",
    categoria: "Botella",
    tipo: "hidratante",
  },
  {
    id: 4,
    nombre: "Jamaica Splash",
    tamaño: "500ml",
    pack : "6 unidades",
    img: "https://res.cloudinary.com/dleem7osr/image/upload/v1733356357/JamaicaSplash-removebg-preview_u2zbkl.png",
    imgDos: "https://res.cloudinary.com/dleem7osr/image/upload/v1733356357/JamaicaSplash-removebg-preview_u2zbkl.png",
    imgTres: "https://res.cloudinary.com/dleem7osr/image/upload/v1733356357/JamaicaSplash-removebg-preview_u2zbkl.png",
    descripcion: "Una bebida vibrante y natural, elaborada con extracto puro de flor de jamaica. Rica en antioxidantes y vitaminas, refresca, revitaliza y ofrece un sabor único y delicioso, sin aditivos artificiales.",
    precio: "19.99",
    categoria: "Botella",
    tipo: "hidratante",
  },
  {
    id: 5,
    nombre: "Pineapple Splash",
    tamaño: "500ml",
    pack : "6 unidades",
    img: "https://res.cloudinary.com/dleem7osr/image/upload/v1733356101/BebidaPineaple-removebg-preview_a9xfgj.png",
    imgDos: "https://res.cloudinary.com/dleem7osr/image/upload/v1733356101/BebidaPineaple-removebg-preview_a9xfgj.png",
    imgTres: "https://i.ibb.co/sCXtMmc/Bebida-Pineaple.jpg",
    descripcion: "Una bebida refrescante y natural, hecha con jugo puro de piña. Rica en vitaminas y antioxidantes, brinda un sabor tropical y revitalizante, ideal para energizar tu día de manera saludable.",
    precio: "19.99",
    categoria: "Botella",
    tipo: "hidratante",
  },
  {
    id: 6,
    nombre: "Lemon Breeze Splash",
    tamaño: "500ml",
    img: "https://res.cloudinary.com/dleem7osr/image/upload/v1733362560/BebidaLimonSplash-removebg-preview_mulr1k.png",
    imgDos: "https://res.cloudinary.com/dleem7osr/image/upload/v1733362560/BebidaLimonSplash-removebg-preview_mulr1k.png",
    imgTres: "https://i.ibb.co/DLGvT4K/Bebida-Limon-Splash.jpg",
    descripcion: "Una bebida natural y revitalizante, elaborada con jugo fresco de limón. Rica en vitamina C y antioxidantes, ofrece un toque cítrico refrescante que energiza y mantiene tu cuerpo hidratado.",

    precio: "19.99",
    categoria: "Botella",
    tipo: "hidratante",
  },

  // Energizantes

  {
    id: 7,
    nombre: "Limonada Detox Power",
    tamaño: "500ml",
    pack : "6 unidades",
    img: "https://res.cloudinary.com/dleem7osr/image/upload/v1733357634/BebidaLimonada-removebg-preview_cp4rft.png",
    imgDos: "https://res.cloudinary.com/dleem7osr/image/upload/v1733357634/BebidaLimonada-removebg-preview_cp4rft.png",
    imgTres: "https://res.cloudinary.com/dleem7osr/image/upload/v1734460114/BebidaLimonada_owktt2.jpg",
    descripcion: " Una bebida energizante natural con limón fresco y extractos revitalizantes. Enriquecida con vitamina C y antioxidantes, proporciona energía sostenida y ayuda a desintoxicar el cuerpo.",
    precio: "19.99",
    categoria: "Botella",
    tipo: "energizante",
  },
  {
    id: 8,
    nombre: "MatchaZen Power",
    tamaño: "500ml",
    pack : "6 unidades",
    img: "https://res.cloudinary.com/dleem7osr/image/upload/v1733363191/MatchPowerBebida-removebg-preview_sfm20p.png",
    imgDos: "https://res.cloudinary.com/dleem7osr/image/upload/v1733363191/MatchPowerBebida-removebg-preview_sfm20p.png",
    imgTres: "https://res.cloudinary.com/dleem7osr/image/upload/v1733363191/MatchPowerBebida-removebg-preview_sfm20p.png",
    descripcion: "Una bebida energizante natural a base de té matcha premium, rica en antioxidantes y L-teanina. Brinda energía limpia y sostenida.",
    precio: "19.99",
    categoria: "Polvo",
    tipo: "energizante",
  },
  {
    id: 9,
    nombre: " Rush de Cacao Power",
    tamaño: "500ml",
    pack : "6 unidades",
    img: "https://res.cloudinary.com/dleem7osr/image/upload/v1733354479/CacaoBebida-removebg-preview_uxrx2q.png",
    imgDos: "https://res.cloudinary.com/dleem7osr/image/upload/v1733354479/CacaoBebida-removebg-preview_uxrx2q.png",
    imgTres: "https://res.cloudinary.com/dleem7osr/image/upload/v1733354479/CacaoBebida-removebg-preview_uxrx2q.png",
    descripcion: "Una bebida energizante natural hecha con cacao puro, rica en antioxidantes, magnesio y teobromina. Proporciona un impulso de energía duradero, mejora tu estado de ánimo.",
    precio: "19.99",
    categoria: "Polvo",
    tipo: "energizante",
  },
  {
    id: 10,
    nombre: "Guaraná Energy Power",
    tamaño: "500ml",
    pack : "6 unidades",
    img: "https://res.cloudinary.com/dleem7osr/image/upload/v1733358481/GuaranaPowers-removebg-preview_lkh9rw.png",
    imgDos: "https://res.cloudinary.com/dleem7osr/image/upload/v1733358481/GuaranaPowers-removebg-preview_lkh9rw.png",
    imgTres: "https://res.cloudinary.com/dleem7osr/image/upload/v1733358481/GuaranaPowers-removebg-preview_lkh9rw.png",
    descripcion: "Una bebida energizante natural con extracto de guaraná, conocido por su capacidad para aumentar la energía, mejorar la concentración y combatir la fatiga. Rico en antioxidantes y nutrientes.",
    precio: "19.99",
    categoria: "Botella",
    tipo: "energizante",
  },
  {
    id: 11,
    nombre: "Dragonfruit Blast Power",
    tamaño: "500ml",
    pack : "6 unidades",
    img: "https://res.cloudinary.com/dleem7osr/image/upload/v1733362954/DragonFruit-removebg-preview_tdbshb.png",
    imgDos: "https://res.cloudinary.com/dleem7osr/image/upload/v1733362954/DragonFruit-removebg-preview_tdbshb.png",
    imgTres: "https://i.ibb.co/93Y33d3/Dragon-Fruit.jpg",
    descripcion: "Una bebida energizante natural con la exótica pitaya o fruta del dragón, rica en vitamina C, antioxidantes y fibra. Perfecta para revitalizar tu cuerpo y mente, brindando energía duradera y una sensación de frescura tropical .",
    precio: "19.99",
    categoria: "Polvo",
    tipo: "energizante",
  },
  {
    id: 12,
    nombre: "Matcha Latte Power",
    tamaño: "599ml",
    pack : "6 unidades",
    img: "https://res.cloudinary.com/dleem7osr/image/upload/v1733354711/BebidaMatchaLate-removebg-preview_ab7awx.png",
    imgDos: "https://res.cloudinary.com/dleem7osr/image/upload/v1733354711/BebidaMatchaLate-removebg-preview_ab7awx.png",
    imgTres: "https://i.ibb.co/L9PkKQZ/Bebida-Matcha-Late.jpg",
    descripcion: "Una bebida energizante natural que combina el poder del matcha con la suavidad de la leche. Cargada de antioxidantes y aminoácidos, esta bebida te proporciona un impulso de energía duradero",
    precio: "19.99",
    categoria: "Polvo",
    tipo: "energizante",
  },
  

  // Nutricionales
  {
    id: 13,
    nombre: "Proteico de Vainilla",
    tamaño: "1.5L",
    pack : "6 unidades",
    img: "https://res.cloudinary.com/dleem7osr/image/upload/v1733361306/ProteicoVanilla-removebg-preview_tsq8qk.png",
    imgDos: "https://res.cloudinary.com/dleem7osr/image/upload/v1733361306/ProteicoVanilla-removebg-preview_tsq8qk.png",
    imgTres: "https://res.cloudinary.com/dleem7osr/image/upload/v1733361306/ProteicoVanilla-removebg-preview_tsq8qk.png",
    descripcion: "Disfruta de una bebida energizante y natural, rica en proteínas esenciales que apoyan tu recuperación muscular. Con el suave y delicioso sabor de la vainilla, es ideal para potenciar tu rendimiento físico.",
    precio: "29.99",
    categoria: "Botella",
    tipo: "nutricional",
  },
  {
    id: 14,
    nombre: "Proteico de Banana",
    tamaño: "1.5L",
    pack : "6 unidades",
    img: "https://res.cloudinary.com/dleem7osr/image/upload/v1733360483/ProteicoBanana-removebg-preview_q4ga1p.png",
    imgDos: "https://res.cloudinary.com/dleem7osr/image/upload/v1733360483/ProteicoBanana-removebg-preview_q4ga1p.png",
    imgTres: "https://res.cloudinary.com/dleem7osr/image/upload/v1733360483/ProteicoBanana-removebg-preview_q4ga1p.png",
    descripcion: "Una bebida natural llena de proteínas que favorecen la recuperación y el crecimiento muscular. Con el sabor dulce y cremoso de la banana.",
    precio: "29.99",
    categoria: "Botella",
    tipo: "nutricional",
  },
  {
    id: 15,
    nombre: "Proteico de Mora Azul",
    tamaño: "1.5L",
    pack : "6 unidades",
    img: "https://res.cloudinary.com/dleem7osr/image/upload/v1733361550/ProteicoMoraAzul-removebg-preview_akbmsu.png",
    imgDos: "https://res.cloudinary.com/dleem7osr/image/upload/v1733361550/ProteicoMoraAzul-removebg-preview_akbmsu.png",
    imgTres: "https://res.cloudinary.com/dleem7osr/image/upload/v1733361550/ProteicoMoraAzul-removebg-preview_akbmsu.png",
    descripcion: "Disfruta de una bebida natural rica en proteínas que ayuda en la recuperación y el desarrollo muscular. Con el sabor refrescante de la mora azul",
    precio: "29.99",
    categoria: "Polvo",
    tipo: "nutricional",
  },
  {
    id: 16,
    nombre: "Proteico de Coco",
    tamaño: "1.5L",
    pack : "6 unidades",
    img: "https://res.cloudinary.com/dleem7osr/image/upload/v1733361742/ProteicoCoco-removebg-preview_k7tewl.png",
    imgDos: "https://res.cloudinary.com/dleem7osr/image/upload/v1733361742/ProteicoCoco-removebg-preview_k7tewl.png",
    imgTres: "https://res.cloudinary.com/dleem7osr/image/upload/v1733361742/ProteicoCoco-removebg-preview_k7tewl.png",
    descripcion: "Un delicioso y cremoso batido natural que combina el exótico sabor del coco con una potente dosis de proteínas. Ideal para la recuperación muscular y el fortalecimiento.",
    precio: "29.99",
    categoria: "Polvo",
    tipo: "nutricional",
  },
  {
    id: 17,
    nombre: "Proteico de Frutos Rojos",
    tamaño: "1.5L",
    pack : "6 unidades",
    img: "https://res.cloudinary.com/dleem7osr/image/upload/v1733360945/ProteicoFrutosRojos-removebg-preview_spp8kl.png",
    imgDos: "https://res.cloudinary.com/dleem7osr/image/upload/v1733360945/ProteicoFrutosRojos-removebg-preview_spp8kl.png",
    imgTres: "https://res.cloudinary.com/dleem7osr/image/upload/v1733360945/ProteicoFrutosRojos-removebg-preview_spp8kl.png",
    descripcion: " Una mezcla deliciosa y natural de fresas, frambuesas y moras, combinada con una alta dosis de proteínas. Perfecto para apoyar tu recuperación muscular, mantenerte energizado y disfrutar de un sabor refrescante.",
    precio: "29.99",
    categoria: "Botella",
    tipo: "nutricional",
  },
  {
    id: 18,
    nombre: "Proteico de Almendra",
    tamaño: "1.5L",
    pack : "6 unidades",
    img: "https://res.cloudinary.com/dleem7osr/image/upload/v1733363539/ProteicoAlmendra-removebg-preview_fwmyt8.png",
    imgDos: "https://res.cloudinary.com/dleem7osr/image/upload/v1733363539/ProteicoAlmendra-removebg-preview_fwmyt8.png",
    imgTres: "https://res.cloudinary.com/dleem7osr/image/upload/v1733363539/ProteicoAlmendra-removebg-preview_fwmyt8.png",
    descripcion: " Una bebida suave y deliciosa, rica en proteínas de alta calidad, que ofrece los beneficios de las almendras para nutrir tu cuerpo. Ideal para aumentar tu energía y promover la recuperación muscular.",
    precio: "29.99",
    categoria: "Botella",
    tipo: "nutricional",
  }
];
